name: first-test
on: [push]
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: git clone 
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with: 
                python-version: '3.9'
            - name: Setup requirements
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: setup pytest
              run: pytest 
            
            